[package]
org = "ballerina"
name = "encoding"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../encoding-native/build/libs/encoding-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "encoding"
version = "@project.version@"
