[package]
org = "ballerina"
name = "url"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../url-native/build/libs/url-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "url"
version = "@project.version@"
